version: '3.8'
services:
  phish-detector-app:
    build: .
    ports:
      - "8080"
    # The 'secrets' section tells Defang to inject the values defined below
    # as environment variables into the running container.
    secrets:
      - SECRET_KEY
      - DATABASE_URL
      - ADMIN_EMAIL
      - ADMIN_PASSWORD

# The 'x-defang' extension is used to define secrets for the deployment.
# IMPORTANT: For production, it is highly recommended to use a secrets manager
# like AWS Secrets Manager instead of putting plaintext values here.
# For local development, you can use a .env file.
x-defang:
  secrets:
    environment:
      SECRET_KEY: "913817ea60927379d177d4e6c21879c50eae5c2bee04810dbd16f17664d7d2e5"
      DATABASE_URL: "postgresql://neondb_owner:npg_u7iJmIGEaw2Z@ep-rough-poetry-ade9k5j8-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      ADMIN_EMAIL: "Adp9550@gmail.com"
      ADMIN_PASSWORD: "ADp95220"