version: '3.8'
services:
  phish-detector-app:
    build: .
    ports:
      - "8080"
    # The 'secrets' section tells Defang to inject these environment variables
    # from its configured secrets store.
    secrets:
      - SECRET_KEY
      - DATABASE_URL
      - ADMIN_EMAIL
      - ADMIN_PASSWORD