version: '3.8'
services:
  # This is the service name, which replaces the --name flag
  phish-detector-app:
    # Tells Defang to build the Docker image using the Dockerfile in the current directory
    build: .
    # The application runs on port 8080, as defined in your Dockerfile
    ports:
      - "8080"
    # All required environment variables are defined here
    # These values should be sourced from a secure location (e.g., a .env file or environment secrets)
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}