version: '3.8'
services:
  phish-detector-app:
    build: .
    ports:
      - "8080"
    secrets:
      - SECRET_KEY
      - DATABASE_URL
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
    # Explicitly configure the healthcheck to use the /health endpoint
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
